


const ALERT = 'ALERT';
const REFETCH_CHATS="REFETCH_CHATS";

const NEW_ATTACHMENT="NEW _ATTACHMENT"
const  NEW_MESSAGE_ALERT="NEW_MESSAGE"

export {ALERT,REFETCH_CHATS,NEW_ATTACHMENT,NEW_MESSAGE_ALERT}